Bump to 1.2, hotfix, initialize sun.misc.Unsafe first...?
- Without this, sun.misc.Unsafe throws a NoClassDefFoundError after removeAllReflectionFilters routine is finished